name: Release Package on PyPi
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  poetry-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Publish to Pypi
        env:
          TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build -u __token__ -p $TOKEN